name: eShopOnWeb Build and Test
# Trigger the workflow on push to main branch or manual trigger
on:
  push:
    branches: [main]
  workflow_dispatch:
# Environment variables used across jobs
env:
  RESOURCE-GROUP: 'rg-eshoponweb-tayson' # Replace NAME with your unique identifier
  LOCATION: 'eastus2' # Choose your Azure region
  TEMPLATE-FILE: '${{ github.workspace }}/infra/webapp.bicep'
  SUBSCRIPTION-ID: 'da7956c3-fa84-4a39-853b-fbf19f65acc6' # Replace with your subscription ID
  WEBAPP-NAME: 'eshoponweb-tayson' # Replace NAME with unique identifier (lowercase, no spaces)
jobs:
  # Build and test job
  buildandtest:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
      # Setup .NET 8.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          dotnet-quality: 'ga'
      # Restore dependencies
      - name: Restore dependencies
        run: dotnet restore ./src/Web/Web.csproj
      # Build the application
      - name: Build
        run: dotnet build ./src/Web/Web.csproj --no-restore --configuration Release
      # Run tests
      - name: Test
        run: dotnet test ./tests/UnitTests/UnitTests.csproj --no-build --verbosity normal --configuration Release
      # Publish the application
      - name: Publish
        run: dotnet publish ./src/Web/Web.csproj --no-build --configuration Release --output ./publish
      # Upload published artifacts
      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish
      # Debug step to list files
      - name: List files for debugging
        run: ls -R
  # Deploy job
  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    steps:
      # ✅ Checkout repo again so infra/ folder exists in this job
      - name: Checkout code
        uses: actions/checkout@v4
      # ✅ Download build artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ./publish
      # ✅ Login to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # ✅ Deploy Azure infrastructure using Bicep
      - name: Deploy Azure resources
        uses: azure/arm-deploy@v2
        id: deploy-infra
        with:
          subscriptionId: ${{ env.SUBSCRIPTION-ID }}
          resourceGroupName: ${{ env.RESOURCE-GROUP }}
          template: infra/webapp.bicep
          parameters: webAppName=${{ env.WEBAPP-NAME }} location=${{ env.LOCATION }}
          failOnStdErr: false
      # ✅ Deploy app to Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP-NAME }}
          package: ./publish
      # ✅ Logout from Azure
      - name: Azure Logout
        run: az logout
